version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  assignees:
  - scionaltera
  ignore:
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 6.a, < 7"
  - dependency-name: org.mockito:mockito-core
    versions:
    - "> 3.3.0, < 3.4"
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.1
  - dependency-name: org.owasp:dependency-check-gradle
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.webjars:bootstrap
    versions:
    - 4.6.0
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: info.solidsoft.gradle.pitest:gradle-pitest-plugin
    versions:
    - 1.5.2
