version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker-hub-username"
    DOCKER_HUB_PASSWORD: "docker-hub-password"

phases:
  install:
    commands:
      - chmod +x ./gradlew
  pre_build:
    commands:
      - export PROJECT_VERSION=v`egrep "^version" build.gradle | cut -f2 -d\'`
      - export BRANCH_TAG=`echo $CODEBUILD_SOURCE_VERSION | sed 's|/|-|g'`
      - echo Project version is ${PROJECT_VERSION}
      - echo Branch tag is ${BRANCH_TAG}
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - docker build -t scionaltera/redemption:latest -f src/main/docker/codebuild/Dockerfile .
  post_build:
    commands:
      - echo "CodeBuild Initiator is ${CODEBUILD_INITIATOR}"
      - |
        if expr "${CODEBUILD_INITIATOR}": "codepipeline*" >/dev/null; then
          docker tag scionaltera/redemption:latest scionaltera/redemption:${PROJECT_VERSION}
          docker push scionaltera/redemption:latest
          docker push scionaltera/redemption:${PROJECT_VERSION}
        else
          docker tag scionaltera/redemption:latest scionaltera/redemption:${BRANCH_TAG}
          docker push scionaltera/redemption:${BRANCH_TAG}
        fi
      - printf '[{"name":"redemption","imageUri":"%s"}]' scionaltera/redemption:${PROJECT_VERSION} > imagedefinitions.json
artifacts:
  files: imagedefinitions.json