#
# This docker-compose.yml is meant to help with local development.
#
# Using docker-compose and this configuration file you can spin up Redemption and all the databases and other
# services it may need all at once to get a fully functional development copy of the software running. This
# environment is also configured to expose the remote debugging port (5005) on Redemption so that you can attach
# your debugger and use breakpoints to examine any problems you may find.
#

version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: redemption
      POSTGRES_PASSWORD: redemption
      POSTGRES_DB: redemption
  redemption:
    image: scionaltera/redemption:latest
    ports:
     - "8080:8080"
     - "5005:5005"
    links:
     - postgres
    env_file: secrets.env
