ALTER TABLE asset MODIFY COLUMN name VARCHAR(191);
ALTER TABLE asset MODIFY COLUMN description VARCHAR(191);
ALTER TABLE asset CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE audit_log MODIFY COLUMN username VARCHAR(191);
ALTER TABLE audit_log MODIFY COLUMN remote_address VARCHAR(191);
ALTER TABLE audit_log MODIFY COLUMN message VARCHAR(191);
ALTER TABLE audit_log CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE participant MODIFY COLUMN first_name VARCHAR(191);
ALTER TABLE participant MODIFY COLUMN last_name VARCHAR(191);
ALTER TABLE participant MODIFY COLUMN email VARCHAR(191);
ALTER TABLE participant CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE staff MODIFY COLUMN username VARCHAR(191);
ALTER TABLE staff MODIFY COLUMN password VARCHAR(191);
ALTER TABLE staff CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE staff_permissions MODIFY COLUMN permissions VARCHAR(191);
ALTER TABLE staff_permissions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE SPRING_SESSION_ATTRIBUTES MODIFY COLUMN ATTRIBUTE_NAME VARCHAR(191);
ALTER TABLE SPRING_SESSION_ATTRIBUTES DROP FOREIGN KEY SPRING_SESSION_ATTRIBUTES_FK;
ALTER TABLE SPRING_SESSION_ATTRIBUTES CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE SPRING_SESSION CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE SPRING_SESSION_ATTRIBUTES ADD FOREIGN KEY SPRING_SESSION_ATTRIBUTES_FK (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE;